# curl -X POST 'http://localhost:8080/accounts' -d '100000'
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "number": id,
  "customerId": id,
  "balance": 10000
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


###
# curl -X POST 'http://localhost:8080/accounts/1/actions/withdraw' -d '1555'
POST http://localhost:8080/accounts/1/actions/withdraw
Content-Type: application/json

1555

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/accounts/all
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/accounts/67077ff41ee4ab3ea18e3734
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

# curl -X PUT 'http://localhost:8080/accounts/670795350c5d64558ce9d199'
PUT http://localhost:8080/accounts/670798e5f498926784fe82e3
Content-Type: application/json

{
  "number": id,
  "customerId": id,
  "balance": "1424211"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

# curl -X DELETE 'http://localhost:8080/accounts/1'
DELETE http://localhost:8080/accounts/670795350c5d64558ce9d199
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}





