# curl -X POST 'http://localhost:8080/accounts/1/actions/create' -d '100000'
POST http://localhost:8080/accounts/1/actions/create
Content-Type: application/json

100000

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


###
# curl -X POST 'http://localhost:8080/accounts/1/actions/withdraw' -d '1555'
POST http://localhost:8080/accounts/1/actions/withdraw
Content-Type: application/json

1555

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


