permissions:
  contents: read
  security-events: write
  id-token: write  # Required for uploading the dependency snapshot

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven and generate SBOM
      run: mvn clean verify -DskipTests

    - name: Upload dependency snapshot (SBOM)
      uses: github/dependency-submission-action@v4
      with:
        sbom-path: target/bom.json
